version: '2'
services:
  newoapp9uaa-postgresql:
    image: postgres:11.3
    # volumes:
    #     - ~/volumes/jhipster/NewoApp9UAA/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=NewoApp9UAA
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
